<?php
$_SESSION['kod_karty_prod'] = '';
$_SESSION['nazwa_wytw'] = '';
$_SESSION['nazwa_wzoru'] = '';
$_SESSION['kod_ean'] = '';
$_SESSION['link_img'] = 'etykieta.png';
$_SESSION['paper'] = '';
$_SESSION['glue'] = '';
$_SESSION['quantity_er'] = '';
$_SESSION['bush'] = '';
$_SESSION['ilosc_uzytkow'] = ''; //sekcja paper glue
$_SESSION['roll_length'] = '';
$_SESSION['kolor'] = '';
//$_POST['kolor'] = '';
$_SESSION['direction_roll'] = '';
$_SESSION['wymiar_x_od'] = '';
$_SESSION['wymiar_x_do'] = 1000 ;
$_SESSION['wymiar_y_do'] = 1000 ;
$_SESSION['wymiar_y_od'] = '';
$_SESSION['circulation'] = '';
$_SESSION['comments_to_order'] = '';
$_SESSION['termin'] = '';
$_SESSION['id_wykrojnik'] = '';
$_SESSION['dimension_x'] = '';
$_SESSION['dimension_y'] = '';
$_SESSION['form'] = '';
$_SESSION['form_link'] = '';
$_SESSION['raw_material'] = '';
$_SESSION['number_of_teeth'] = '';
$_SESSION['uzytkow'] = '';	// saekcja wykrojniki
$_SESSION['reps'] = '';
$_SESSION['radius'] = '';
$_SESSION['date_of_completion'] = '';
$_SESSION['raw_material_lenght'] = '';
$_SESSION['form_material_width'] = '';
$_SESSION['material_width'] = '';
$_SESSION['comments_to_order'] = '';
$_SESSION['print_report'] = '';
$_SESSION['date_of_insertion'] = '';
$_SESSION['date_of_edition'] = '';
//$_SESSION['id_autora'] = '';
$_SESSION['number_of_rolls'] = '';
$_SESSION['actual_amount_of_material_used'] = 'wpisz i zatwierdź >>';
$_SESSION['scrolled_amount'] = 'wpisz i zatwierdź >>';
$_SESSION['invoice_number'] = 'wpisz i zatwierdź >>';
$_SESSION['end_date'] = '';
$_SESSION['search_kod_karty_prod'] = ''; //zmienne wyszukiwarek kasowane są w programie po kazdym wyszukaniu
$_SESSION['search_nazwa_wytw'] = '';  //zmienne wyszukiwarek kasowane są w programie po kazdym wyszukaniu
$_SESSION['search_nazwa_wzoru'] = '';  //zmienne wyszukiwarek kasowane są w programie po kazdym wyszukaniu
$_SESSION['search_kod_ean'] = '' ;  //zmienne wyszukiwarek kasowane są w programie po kazdym wyszukaniu
// $_POST['uzytkow'] = '' ;//dla prawidłowego działania necessary_variables.php
// $_POST['reps'] = '' ; //dla prawidłowego działania necessary_variables.php
// $_POST['direction_roll'] = '' ; //dla prawidłowego działania necessary_variables.php
$_SESSION['mode'] = '';
?>
